### ISSUE TITLE
JOSS Review: Raw HTML is found in page titles

### ISSUE THREAD

**Issue by elimillera** [pratheesh3780/grapesAgri1#3]
Hello 👋 

The use of tags in `titlePanel` results in raw html being displayed in the page title. Using the `windowTitle` argument will override this behavior.

![image](https://user-images.githubusercontent.com/24767886/125377299-5eaab000-e352-11eb-9d73-059bf2ae040d.png)

**Comment by pratheesh3780** [comment]
Hi,
WindowTitle added
